services:
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "9096:8090"
    env_file:
      - ${ENV_FILE:-.env}
    networks:
      - default
      - external-network

volumes:
  centropy_affilate_postgres_data:

networks:
  external-network:
    external: true
