// Code generated by ent, DO NOT EDIT.

package complaintverification

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the complaintverification type in the database.
	Label = "complaint_verification"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldExternalUserID holds the string denoting the external_user_id field in the database.
	FieldExternalUserID = "external_user_id"
	// FieldComplaintAt holds the string denoting the complaint_at field in the database.
	FieldComplaintAt = "complaint_at"
	// FieldIsGenuine holds the string denoting the is_genuine field in the database.
	FieldIsGenuine = "is_genuine"
	// FieldReasoning holds the string denoting the reasoning field in the database.
	FieldReasoning = "reasoning"
	// FieldVerifiedAt holds the string denoting the verified_at field in the database.
	FieldVerifiedAt = "verified_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the complaintverification in the database.
	Table = "complaint_verifications"
)

// Columns holds all SQL columns for complaintverification fields.
var Columns = []string{
	FieldID,
	FieldExternalUserID,
	FieldComplaintAt,
	FieldIsGenuine,
	FieldReasoning,
	FieldVerifiedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ComplaintVerification queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByExternalUserID orders the results by the external_user_id field.
func ByExternalUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalUserID, opts...).ToFunc()
}

// ByComplaintAt orders the results by the complaint_at field.
func ByComplaintAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldComplaintAt, opts...).ToFunc()
}

// ByIsGenuine orders the results by the is_genuine field.
func ByIsGenuine(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsGenuine, opts...).ToFunc()
}

// ByReasoning orders the results by the reasoning field.
func ByReasoning(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReasoning, opts...).ToFunc()
}

// ByVerifiedAt orders the results by the verified_at field.
func ByVerifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerifiedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
