// Code generated by ent, DO NOT EDIT.

package complaintverification

import (
	"centropy-affilate/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldLTE(FieldID, id))
}

// ExternalUserID applies equality check predicate on the "external_user_id" field. It's identical to ExternalUserIDEQ.
func ExternalUserID(v uuid.UUID) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldEQ(FieldExternalUserID, v))
}

// ComplaintAt applies equality check predicate on the "complaint_at" field. It's identical to ComplaintAtEQ.
func ComplaintAt(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldEQ(FieldComplaintAt, v))
}

// IsGenuine applies equality check predicate on the "is_genuine" field. It's identical to IsGenuineEQ.
func IsGenuine(v bool) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldEQ(FieldIsGenuine, v))
}

// Reasoning applies equality check predicate on the "reasoning" field. It's identical to ReasoningEQ.
func Reasoning(v string) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldEQ(FieldReasoning, v))
}

// VerifiedAt applies equality check predicate on the "verified_at" field. It's identical to VerifiedAtEQ.
func VerifiedAt(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldEQ(FieldVerifiedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldEQ(FieldUpdatedAt, v))
}

// ExternalUserIDEQ applies the EQ predicate on the "external_user_id" field.
func ExternalUserIDEQ(v uuid.UUID) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldEQ(FieldExternalUserID, v))
}

// ExternalUserIDNEQ applies the NEQ predicate on the "external_user_id" field.
func ExternalUserIDNEQ(v uuid.UUID) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldNEQ(FieldExternalUserID, v))
}

// ExternalUserIDIn applies the In predicate on the "external_user_id" field.
func ExternalUserIDIn(vs ...uuid.UUID) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldIn(FieldExternalUserID, vs...))
}

// ExternalUserIDNotIn applies the NotIn predicate on the "external_user_id" field.
func ExternalUserIDNotIn(vs ...uuid.UUID) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldNotIn(FieldExternalUserID, vs...))
}

// ExternalUserIDGT applies the GT predicate on the "external_user_id" field.
func ExternalUserIDGT(v uuid.UUID) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldGT(FieldExternalUserID, v))
}

// ExternalUserIDGTE applies the GTE predicate on the "external_user_id" field.
func ExternalUserIDGTE(v uuid.UUID) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldGTE(FieldExternalUserID, v))
}

// ExternalUserIDLT applies the LT predicate on the "external_user_id" field.
func ExternalUserIDLT(v uuid.UUID) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldLT(FieldExternalUserID, v))
}

// ExternalUserIDLTE applies the LTE predicate on the "external_user_id" field.
func ExternalUserIDLTE(v uuid.UUID) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldLTE(FieldExternalUserID, v))
}

// ComplaintAtEQ applies the EQ predicate on the "complaint_at" field.
func ComplaintAtEQ(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldEQ(FieldComplaintAt, v))
}

// ComplaintAtNEQ applies the NEQ predicate on the "complaint_at" field.
func ComplaintAtNEQ(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldNEQ(FieldComplaintAt, v))
}

// ComplaintAtIn applies the In predicate on the "complaint_at" field.
func ComplaintAtIn(vs ...time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldIn(FieldComplaintAt, vs...))
}

// ComplaintAtNotIn applies the NotIn predicate on the "complaint_at" field.
func ComplaintAtNotIn(vs ...time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldNotIn(FieldComplaintAt, vs...))
}

// ComplaintAtGT applies the GT predicate on the "complaint_at" field.
func ComplaintAtGT(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldGT(FieldComplaintAt, v))
}

// ComplaintAtGTE applies the GTE predicate on the "complaint_at" field.
func ComplaintAtGTE(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldGTE(FieldComplaintAt, v))
}

// ComplaintAtLT applies the LT predicate on the "complaint_at" field.
func ComplaintAtLT(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldLT(FieldComplaintAt, v))
}

// ComplaintAtLTE applies the LTE predicate on the "complaint_at" field.
func ComplaintAtLTE(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldLTE(FieldComplaintAt, v))
}

// IsGenuineEQ applies the EQ predicate on the "is_genuine" field.
func IsGenuineEQ(v bool) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldEQ(FieldIsGenuine, v))
}

// IsGenuineNEQ applies the NEQ predicate on the "is_genuine" field.
func IsGenuineNEQ(v bool) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldNEQ(FieldIsGenuine, v))
}

// ReasoningEQ applies the EQ predicate on the "reasoning" field.
func ReasoningEQ(v string) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldEQ(FieldReasoning, v))
}

// ReasoningNEQ applies the NEQ predicate on the "reasoning" field.
func ReasoningNEQ(v string) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldNEQ(FieldReasoning, v))
}

// ReasoningIn applies the In predicate on the "reasoning" field.
func ReasoningIn(vs ...string) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldIn(FieldReasoning, vs...))
}

// ReasoningNotIn applies the NotIn predicate on the "reasoning" field.
func ReasoningNotIn(vs ...string) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldNotIn(FieldReasoning, vs...))
}

// ReasoningGT applies the GT predicate on the "reasoning" field.
func ReasoningGT(v string) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldGT(FieldReasoning, v))
}

// ReasoningGTE applies the GTE predicate on the "reasoning" field.
func ReasoningGTE(v string) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldGTE(FieldReasoning, v))
}

// ReasoningLT applies the LT predicate on the "reasoning" field.
func ReasoningLT(v string) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldLT(FieldReasoning, v))
}

// ReasoningLTE applies the LTE predicate on the "reasoning" field.
func ReasoningLTE(v string) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldLTE(FieldReasoning, v))
}

// ReasoningContains applies the Contains predicate on the "reasoning" field.
func ReasoningContains(v string) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldContains(FieldReasoning, v))
}

// ReasoningHasPrefix applies the HasPrefix predicate on the "reasoning" field.
func ReasoningHasPrefix(v string) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldHasPrefix(FieldReasoning, v))
}

// ReasoningHasSuffix applies the HasSuffix predicate on the "reasoning" field.
func ReasoningHasSuffix(v string) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldHasSuffix(FieldReasoning, v))
}

// ReasoningEqualFold applies the EqualFold predicate on the "reasoning" field.
func ReasoningEqualFold(v string) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldEqualFold(FieldReasoning, v))
}

// ReasoningContainsFold applies the ContainsFold predicate on the "reasoning" field.
func ReasoningContainsFold(v string) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldContainsFold(FieldReasoning, v))
}

// VerifiedAtEQ applies the EQ predicate on the "verified_at" field.
func VerifiedAtEQ(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldEQ(FieldVerifiedAt, v))
}

// VerifiedAtNEQ applies the NEQ predicate on the "verified_at" field.
func VerifiedAtNEQ(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldNEQ(FieldVerifiedAt, v))
}

// VerifiedAtIn applies the In predicate on the "verified_at" field.
func VerifiedAtIn(vs ...time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldIn(FieldVerifiedAt, vs...))
}

// VerifiedAtNotIn applies the NotIn predicate on the "verified_at" field.
func VerifiedAtNotIn(vs ...time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldNotIn(FieldVerifiedAt, vs...))
}

// VerifiedAtGT applies the GT predicate on the "verified_at" field.
func VerifiedAtGT(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldGT(FieldVerifiedAt, v))
}

// VerifiedAtGTE applies the GTE predicate on the "verified_at" field.
func VerifiedAtGTE(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldGTE(FieldVerifiedAt, v))
}

// VerifiedAtLT applies the LT predicate on the "verified_at" field.
func VerifiedAtLT(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldLT(FieldVerifiedAt, v))
}

// VerifiedAtLTE applies the LTE predicate on the "verified_at" field.
func VerifiedAtLTE(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldLTE(FieldVerifiedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ComplaintVerification) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ComplaintVerification) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ComplaintVerification) predicate.ComplaintVerification {
	return predicate.ComplaintVerification(sql.NotPredicates(p))
}
