// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AdminUsersColumns holds the columns for the "admin_users" table.
	AdminUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 160},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Nullable: true, Size: 120},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AdminUsersTable holds the schema information for the "admin_users" table.
	AdminUsersTable = &schema.Table{
		Name:       "admin_users",
		Columns:    AdminUsersColumns,
		PrimaryKey: []*schema.Column{AdminUsersColumns[0]},
	}
	// ComplaintVerificationsColumns holds the columns for the "complaint_verifications" table.
	ComplaintVerificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "external_user_id", Type: field.TypeUUID},
		{Name: "complaint_at", Type: field.TypeTime},
		{Name: "is_genuine", Type: field.TypeBool},
		{Name: "reasoning", Type: field.TypeString, Size: 2147483647},
		{Name: "verified_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ComplaintVerificationsTable holds the schema information for the "complaint_verifications" table.
	ComplaintVerificationsTable = &schema.Table{
		Name:       "complaint_verifications",
		Columns:    ComplaintVerificationsColumns,
		PrimaryKey: []*schema.Column{ComplaintVerificationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "complaintverification_external_user_id",
				Unique:  true,
				Columns: []*schema.Column{ComplaintVerificationsColumns[1]},
			},
		},
	}
	// CustomersColumns holds the columns for the "customers" table.
	CustomersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "external_user_id", Type: field.TypeUUID},
		{Name: "phone", Type: field.TypeString, Size: 20},
		{Name: "first_name", Type: field.TypeString, Nullable: true, Size: 200},
		{Name: "last_name", Type: field.TypeString, Nullable: true, Size: 200},
		{Name: "registered_at", Type: field.TypeTime},
		{Name: "last_synced_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CustomersTable holds the schema information for the "customers" table.
	CustomersTable = &schema.Table{
		Name:       "customers",
		Columns:    CustomersColumns,
		PrimaryKey: []*schema.Column{CustomersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "customer_external_user_id",
				Unique:  true,
				Columns: []*schema.Column{CustomersColumns[1]},
			},
			{
				Name:    "customer_phone",
				Unique:  false,
				Columns: []*schema.Column{CustomersColumns[2]},
			},
		},
	}
	// CustomerAnalysesColumns holds the columns for the "customer_analyses" table.
	CustomerAnalysesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "external_user_id", Type: field.TypeUUID},
		{Name: "category", Type: field.TypeEnum, Enums: []string{"PROGRAM_DELAY", "PRICE", "SUPPORT_QUALITY", "TECHNICAL_ISSUE", "HEALTH_PERSONAL", "LOST_INTEREST", "UNCLEAR", "NO_MESSAGES"}},
		{Name: "summary", Type: field.TypeString, Size: 2147483647},
		{Name: "confidence", Type: field.TypeEnum, Enums: []string{"high", "medium", "low"}, Default: "low"},
		{Name: "last_message_at", Type: field.TypeTime, Nullable: true},
		{Name: "analyzed_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CustomerAnalysesTable holds the schema information for the "customer_analyses" table.
	CustomerAnalysesTable = &schema.Table{
		Name:       "customer_analyses",
		Columns:    CustomerAnalysesColumns,
		PrimaryKey: []*schema.Column{CustomerAnalysesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "customeranalysis_external_user_id",
				Unique:  true,
				Columns: []*schema.Column{CustomerAnalysesColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdminUsersTable,
		ComplaintVerificationsTable,
		CustomersTable,
		CustomerAnalysesTable,
	}
)

func init() {
}
