// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"centropy-affilate/ent/migrate"

	"centropy-affilate/ent/adminuser"
	"centropy-affilate/ent/complaintverification"
	"centropy-affilate/ent/customer"
	"centropy-affilate/ent/customeranalysis"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AdminUser is the client for interacting with the AdminUser builders.
	AdminUser *AdminUserClient
	// ComplaintVerification is the client for interacting with the ComplaintVerification builders.
	ComplaintVerification *ComplaintVerificationClient
	// Customer is the client for interacting with the Customer builders.
	Customer *CustomerClient
	// CustomerAnalysis is the client for interacting with the CustomerAnalysis builders.
	CustomerAnalysis *CustomerAnalysisClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AdminUser = NewAdminUserClient(c.config)
	c.ComplaintVerification = NewComplaintVerificationClient(c.config)
	c.Customer = NewCustomerClient(c.config)
	c.CustomerAnalysis = NewCustomerAnalysisClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                   ctx,
		config:                cfg,
		AdminUser:             NewAdminUserClient(cfg),
		ComplaintVerification: NewComplaintVerificationClient(cfg),
		Customer:              NewCustomerClient(cfg),
		CustomerAnalysis:      NewCustomerAnalysisClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                   ctx,
		config:                cfg,
		AdminUser:             NewAdminUserClient(cfg),
		ComplaintVerification: NewComplaintVerificationClient(cfg),
		Customer:              NewCustomerClient(cfg),
		CustomerAnalysis:      NewCustomerAnalysisClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AdminUser.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.AdminUser.Use(hooks...)
	c.ComplaintVerification.Use(hooks...)
	c.Customer.Use(hooks...)
	c.CustomerAnalysis.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.AdminUser.Intercept(interceptors...)
	c.ComplaintVerification.Intercept(interceptors...)
	c.Customer.Intercept(interceptors...)
	c.CustomerAnalysis.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AdminUserMutation:
		return c.AdminUser.mutate(ctx, m)
	case *ComplaintVerificationMutation:
		return c.ComplaintVerification.mutate(ctx, m)
	case *CustomerMutation:
		return c.Customer.mutate(ctx, m)
	case *CustomerAnalysisMutation:
		return c.CustomerAnalysis.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AdminUserClient is a client for the AdminUser schema.
type AdminUserClient struct {
	config
}

// NewAdminUserClient returns a client for the AdminUser from the given config.
func NewAdminUserClient(c config) *AdminUserClient {
	return &AdminUserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `adminuser.Hooks(f(g(h())))`.
func (c *AdminUserClient) Use(hooks ...Hook) {
	c.hooks.AdminUser = append(c.hooks.AdminUser, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `adminuser.Intercept(f(g(h())))`.
func (c *AdminUserClient) Intercept(interceptors ...Interceptor) {
	c.inters.AdminUser = append(c.inters.AdminUser, interceptors...)
}

// Create returns a builder for creating a AdminUser entity.
func (c *AdminUserClient) Create() *AdminUserCreate {
	mutation := newAdminUserMutation(c.config, OpCreate)
	return &AdminUserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AdminUser entities.
func (c *AdminUserClient) CreateBulk(builders ...*AdminUserCreate) *AdminUserCreateBulk {
	return &AdminUserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AdminUserClient) MapCreateBulk(slice any, setFunc func(*AdminUserCreate, int)) *AdminUserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AdminUserCreateBulk{err: fmt.Errorf("calling to AdminUserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AdminUserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AdminUserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AdminUser.
func (c *AdminUserClient) Update() *AdminUserUpdate {
	mutation := newAdminUserMutation(c.config, OpUpdate)
	return &AdminUserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AdminUserClient) UpdateOne(_m *AdminUser) *AdminUserUpdateOne {
	mutation := newAdminUserMutation(c.config, OpUpdateOne, withAdminUser(_m))
	return &AdminUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AdminUserClient) UpdateOneID(id uuid.UUID) *AdminUserUpdateOne {
	mutation := newAdminUserMutation(c.config, OpUpdateOne, withAdminUserID(id))
	return &AdminUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AdminUser.
func (c *AdminUserClient) Delete() *AdminUserDelete {
	mutation := newAdminUserMutation(c.config, OpDelete)
	return &AdminUserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AdminUserClient) DeleteOne(_m *AdminUser) *AdminUserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AdminUserClient) DeleteOneID(id uuid.UUID) *AdminUserDeleteOne {
	builder := c.Delete().Where(adminuser.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AdminUserDeleteOne{builder}
}

// Query returns a query builder for AdminUser.
func (c *AdminUserClient) Query() *AdminUserQuery {
	return &AdminUserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAdminUser},
		inters: c.Interceptors(),
	}
}

// Get returns a AdminUser entity by its id.
func (c *AdminUserClient) Get(ctx context.Context, id uuid.UUID) (*AdminUser, error) {
	return c.Query().Where(adminuser.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AdminUserClient) GetX(ctx context.Context, id uuid.UUID) *AdminUser {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AdminUserClient) Hooks() []Hook {
	return c.hooks.AdminUser
}

// Interceptors returns the client interceptors.
func (c *AdminUserClient) Interceptors() []Interceptor {
	return c.inters.AdminUser
}

func (c *AdminUserClient) mutate(ctx context.Context, m *AdminUserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AdminUserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AdminUserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AdminUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AdminUserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AdminUser mutation op: %q", m.Op())
	}
}

// ComplaintVerificationClient is a client for the ComplaintVerification schema.
type ComplaintVerificationClient struct {
	config
}

// NewComplaintVerificationClient returns a client for the ComplaintVerification from the given config.
func NewComplaintVerificationClient(c config) *ComplaintVerificationClient {
	return &ComplaintVerificationClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `complaintverification.Hooks(f(g(h())))`.
func (c *ComplaintVerificationClient) Use(hooks ...Hook) {
	c.hooks.ComplaintVerification = append(c.hooks.ComplaintVerification, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `complaintverification.Intercept(f(g(h())))`.
func (c *ComplaintVerificationClient) Intercept(interceptors ...Interceptor) {
	c.inters.ComplaintVerification = append(c.inters.ComplaintVerification, interceptors...)
}

// Create returns a builder for creating a ComplaintVerification entity.
func (c *ComplaintVerificationClient) Create() *ComplaintVerificationCreate {
	mutation := newComplaintVerificationMutation(c.config, OpCreate)
	return &ComplaintVerificationCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ComplaintVerification entities.
func (c *ComplaintVerificationClient) CreateBulk(builders ...*ComplaintVerificationCreate) *ComplaintVerificationCreateBulk {
	return &ComplaintVerificationCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ComplaintVerificationClient) MapCreateBulk(slice any, setFunc func(*ComplaintVerificationCreate, int)) *ComplaintVerificationCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ComplaintVerificationCreateBulk{err: fmt.Errorf("calling to ComplaintVerificationClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ComplaintVerificationCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ComplaintVerificationCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ComplaintVerification.
func (c *ComplaintVerificationClient) Update() *ComplaintVerificationUpdate {
	mutation := newComplaintVerificationMutation(c.config, OpUpdate)
	return &ComplaintVerificationUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ComplaintVerificationClient) UpdateOne(_m *ComplaintVerification) *ComplaintVerificationUpdateOne {
	mutation := newComplaintVerificationMutation(c.config, OpUpdateOne, withComplaintVerification(_m))
	return &ComplaintVerificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ComplaintVerificationClient) UpdateOneID(id uuid.UUID) *ComplaintVerificationUpdateOne {
	mutation := newComplaintVerificationMutation(c.config, OpUpdateOne, withComplaintVerificationID(id))
	return &ComplaintVerificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ComplaintVerification.
func (c *ComplaintVerificationClient) Delete() *ComplaintVerificationDelete {
	mutation := newComplaintVerificationMutation(c.config, OpDelete)
	return &ComplaintVerificationDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ComplaintVerificationClient) DeleteOne(_m *ComplaintVerification) *ComplaintVerificationDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ComplaintVerificationClient) DeleteOneID(id uuid.UUID) *ComplaintVerificationDeleteOne {
	builder := c.Delete().Where(complaintverification.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ComplaintVerificationDeleteOne{builder}
}

// Query returns a query builder for ComplaintVerification.
func (c *ComplaintVerificationClient) Query() *ComplaintVerificationQuery {
	return &ComplaintVerificationQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeComplaintVerification},
		inters: c.Interceptors(),
	}
}

// Get returns a ComplaintVerification entity by its id.
func (c *ComplaintVerificationClient) Get(ctx context.Context, id uuid.UUID) (*ComplaintVerification, error) {
	return c.Query().Where(complaintverification.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ComplaintVerificationClient) GetX(ctx context.Context, id uuid.UUID) *ComplaintVerification {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ComplaintVerificationClient) Hooks() []Hook {
	return c.hooks.ComplaintVerification
}

// Interceptors returns the client interceptors.
func (c *ComplaintVerificationClient) Interceptors() []Interceptor {
	return c.inters.ComplaintVerification
}

func (c *ComplaintVerificationClient) mutate(ctx context.Context, m *ComplaintVerificationMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ComplaintVerificationCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ComplaintVerificationUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ComplaintVerificationUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ComplaintVerificationDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ComplaintVerification mutation op: %q", m.Op())
	}
}

// CustomerClient is a client for the Customer schema.
type CustomerClient struct {
	config
}

// NewCustomerClient returns a client for the Customer from the given config.
func NewCustomerClient(c config) *CustomerClient {
	return &CustomerClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `customer.Hooks(f(g(h())))`.
func (c *CustomerClient) Use(hooks ...Hook) {
	c.hooks.Customer = append(c.hooks.Customer, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `customer.Intercept(f(g(h())))`.
func (c *CustomerClient) Intercept(interceptors ...Interceptor) {
	c.inters.Customer = append(c.inters.Customer, interceptors...)
}

// Create returns a builder for creating a Customer entity.
func (c *CustomerClient) Create() *CustomerCreate {
	mutation := newCustomerMutation(c.config, OpCreate)
	return &CustomerCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Customer entities.
func (c *CustomerClient) CreateBulk(builders ...*CustomerCreate) *CustomerCreateBulk {
	return &CustomerCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CustomerClient) MapCreateBulk(slice any, setFunc func(*CustomerCreate, int)) *CustomerCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CustomerCreateBulk{err: fmt.Errorf("calling to CustomerClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CustomerCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CustomerCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Customer.
func (c *CustomerClient) Update() *CustomerUpdate {
	mutation := newCustomerMutation(c.config, OpUpdate)
	return &CustomerUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CustomerClient) UpdateOne(_m *Customer) *CustomerUpdateOne {
	mutation := newCustomerMutation(c.config, OpUpdateOne, withCustomer(_m))
	return &CustomerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CustomerClient) UpdateOneID(id uuid.UUID) *CustomerUpdateOne {
	mutation := newCustomerMutation(c.config, OpUpdateOne, withCustomerID(id))
	return &CustomerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Customer.
func (c *CustomerClient) Delete() *CustomerDelete {
	mutation := newCustomerMutation(c.config, OpDelete)
	return &CustomerDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CustomerClient) DeleteOne(_m *Customer) *CustomerDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CustomerClient) DeleteOneID(id uuid.UUID) *CustomerDeleteOne {
	builder := c.Delete().Where(customer.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CustomerDeleteOne{builder}
}

// Query returns a query builder for Customer.
func (c *CustomerClient) Query() *CustomerQuery {
	return &CustomerQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCustomer},
		inters: c.Interceptors(),
	}
}

// Get returns a Customer entity by its id.
func (c *CustomerClient) Get(ctx context.Context, id uuid.UUID) (*Customer, error) {
	return c.Query().Where(customer.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CustomerClient) GetX(ctx context.Context, id uuid.UUID) *Customer {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CustomerClient) Hooks() []Hook {
	return c.hooks.Customer
}

// Interceptors returns the client interceptors.
func (c *CustomerClient) Interceptors() []Interceptor {
	return c.inters.Customer
}

func (c *CustomerClient) mutate(ctx context.Context, m *CustomerMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CustomerCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CustomerUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CustomerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CustomerDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Customer mutation op: %q", m.Op())
	}
}

// CustomerAnalysisClient is a client for the CustomerAnalysis schema.
type CustomerAnalysisClient struct {
	config
}

// NewCustomerAnalysisClient returns a client for the CustomerAnalysis from the given config.
func NewCustomerAnalysisClient(c config) *CustomerAnalysisClient {
	return &CustomerAnalysisClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `customeranalysis.Hooks(f(g(h())))`.
func (c *CustomerAnalysisClient) Use(hooks ...Hook) {
	c.hooks.CustomerAnalysis = append(c.hooks.CustomerAnalysis, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `customeranalysis.Intercept(f(g(h())))`.
func (c *CustomerAnalysisClient) Intercept(interceptors ...Interceptor) {
	c.inters.CustomerAnalysis = append(c.inters.CustomerAnalysis, interceptors...)
}

// Create returns a builder for creating a CustomerAnalysis entity.
func (c *CustomerAnalysisClient) Create() *CustomerAnalysisCreate {
	mutation := newCustomerAnalysisMutation(c.config, OpCreate)
	return &CustomerAnalysisCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CustomerAnalysis entities.
func (c *CustomerAnalysisClient) CreateBulk(builders ...*CustomerAnalysisCreate) *CustomerAnalysisCreateBulk {
	return &CustomerAnalysisCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CustomerAnalysisClient) MapCreateBulk(slice any, setFunc func(*CustomerAnalysisCreate, int)) *CustomerAnalysisCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CustomerAnalysisCreateBulk{err: fmt.Errorf("calling to CustomerAnalysisClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CustomerAnalysisCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CustomerAnalysisCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CustomerAnalysis.
func (c *CustomerAnalysisClient) Update() *CustomerAnalysisUpdate {
	mutation := newCustomerAnalysisMutation(c.config, OpUpdate)
	return &CustomerAnalysisUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CustomerAnalysisClient) UpdateOne(_m *CustomerAnalysis) *CustomerAnalysisUpdateOne {
	mutation := newCustomerAnalysisMutation(c.config, OpUpdateOne, withCustomerAnalysis(_m))
	return &CustomerAnalysisUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CustomerAnalysisClient) UpdateOneID(id uuid.UUID) *CustomerAnalysisUpdateOne {
	mutation := newCustomerAnalysisMutation(c.config, OpUpdateOne, withCustomerAnalysisID(id))
	return &CustomerAnalysisUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CustomerAnalysis.
func (c *CustomerAnalysisClient) Delete() *CustomerAnalysisDelete {
	mutation := newCustomerAnalysisMutation(c.config, OpDelete)
	return &CustomerAnalysisDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CustomerAnalysisClient) DeleteOne(_m *CustomerAnalysis) *CustomerAnalysisDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CustomerAnalysisClient) DeleteOneID(id uuid.UUID) *CustomerAnalysisDeleteOne {
	builder := c.Delete().Where(customeranalysis.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CustomerAnalysisDeleteOne{builder}
}

// Query returns a query builder for CustomerAnalysis.
func (c *CustomerAnalysisClient) Query() *CustomerAnalysisQuery {
	return &CustomerAnalysisQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCustomerAnalysis},
		inters: c.Interceptors(),
	}
}

// Get returns a CustomerAnalysis entity by its id.
func (c *CustomerAnalysisClient) Get(ctx context.Context, id uuid.UUID) (*CustomerAnalysis, error) {
	return c.Query().Where(customeranalysis.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CustomerAnalysisClient) GetX(ctx context.Context, id uuid.UUID) *CustomerAnalysis {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CustomerAnalysisClient) Hooks() []Hook {
	return c.hooks.CustomerAnalysis
}

// Interceptors returns the client interceptors.
func (c *CustomerAnalysisClient) Interceptors() []Interceptor {
	return c.inters.CustomerAnalysis
}

func (c *CustomerAnalysisClient) mutate(ctx context.Context, m *CustomerAnalysisMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CustomerAnalysisCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CustomerAnalysisUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CustomerAnalysisUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CustomerAnalysisDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CustomerAnalysis mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AdminUser, ComplaintVerification, Customer, CustomerAnalysis []ent.Hook
	}
	inters struct {
		AdminUser, ComplaintVerification, Customer, CustomerAnalysis []ent.Interceptor
	}
)
