// Code generated by ent, DO NOT EDIT.

package ent

import (
	"centropy-affilate/ent/complaintverification"
	"centropy-affilate/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ComplaintVerificationDelete is the builder for deleting a ComplaintVerification entity.
type ComplaintVerificationDelete struct {
	config
	hooks    []Hook
	mutation *ComplaintVerificationMutation
}

// Where appends a list predicates to the ComplaintVerificationDelete builder.
func (_d *ComplaintVerificationDelete) Where(ps ...predicate.ComplaintVerification) *ComplaintVerificationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ComplaintVerificationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ComplaintVerificationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ComplaintVerificationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(complaintverification.Table, sqlgraph.NewFieldSpec(complaintverification.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ComplaintVerificationDeleteOne is the builder for deleting a single ComplaintVerification entity.
type ComplaintVerificationDeleteOne struct {
	_d *ComplaintVerificationDelete
}

// Where appends a list predicates to the ComplaintVerificationDelete builder.
func (_d *ComplaintVerificationDeleteOne) Where(ps ...predicate.ComplaintVerification) *ComplaintVerificationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ComplaintVerificationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{complaintverification.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ComplaintVerificationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
