// Code generated by ent, DO NOT EDIT.

package ent

import (
	"centropy-affilate/ent/complaintverification"
	"centropy-affilate/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ComplaintVerificationUpdate is the builder for updating ComplaintVerification entities.
type ComplaintVerificationUpdate struct {
	config
	hooks     []Hook
	mutation  *ComplaintVerificationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ComplaintVerificationUpdate builder.
func (_u *ComplaintVerificationUpdate) Where(ps ...predicate.ComplaintVerification) *ComplaintVerificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetComplaintAt sets the "complaint_at" field.
func (_u *ComplaintVerificationUpdate) SetComplaintAt(v time.Time) *ComplaintVerificationUpdate {
	_u.mutation.SetComplaintAt(v)
	return _u
}

// SetNillableComplaintAt sets the "complaint_at" field if the given value is not nil.
func (_u *ComplaintVerificationUpdate) SetNillableComplaintAt(v *time.Time) *ComplaintVerificationUpdate {
	if v != nil {
		_u.SetComplaintAt(*v)
	}
	return _u
}

// SetIsGenuine sets the "is_genuine" field.
func (_u *ComplaintVerificationUpdate) SetIsGenuine(v bool) *ComplaintVerificationUpdate {
	_u.mutation.SetIsGenuine(v)
	return _u
}

// SetNillableIsGenuine sets the "is_genuine" field if the given value is not nil.
func (_u *ComplaintVerificationUpdate) SetNillableIsGenuine(v *bool) *ComplaintVerificationUpdate {
	if v != nil {
		_u.SetIsGenuine(*v)
	}
	return _u
}

// SetReasoning sets the "reasoning" field.
func (_u *ComplaintVerificationUpdate) SetReasoning(v string) *ComplaintVerificationUpdate {
	_u.mutation.SetReasoning(v)
	return _u
}

// SetNillableReasoning sets the "reasoning" field if the given value is not nil.
func (_u *ComplaintVerificationUpdate) SetNillableReasoning(v *string) *ComplaintVerificationUpdate {
	if v != nil {
		_u.SetReasoning(*v)
	}
	return _u
}

// SetVerifiedAt sets the "verified_at" field.
func (_u *ComplaintVerificationUpdate) SetVerifiedAt(v time.Time) *ComplaintVerificationUpdate {
	_u.mutation.SetVerifiedAt(v)
	return _u
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *ComplaintVerificationUpdate) SetNillableVerifiedAt(v *time.Time) *ComplaintVerificationUpdate {
	if v != nil {
		_u.SetVerifiedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ComplaintVerificationUpdate) SetUpdatedAt(v time.Time) *ComplaintVerificationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ComplaintVerificationMutation object of the builder.
func (_u *ComplaintVerificationUpdate) Mutation() *ComplaintVerificationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ComplaintVerificationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ComplaintVerificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ComplaintVerificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ComplaintVerificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ComplaintVerificationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := complaintverification.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ComplaintVerificationUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ComplaintVerificationUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ComplaintVerificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(complaintverification.Table, complaintverification.Columns, sqlgraph.NewFieldSpec(complaintverification.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ComplaintAt(); ok {
		_spec.SetField(complaintverification.FieldComplaintAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsGenuine(); ok {
		_spec.SetField(complaintverification.FieldIsGenuine, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Reasoning(); ok {
		_spec.SetField(complaintverification.FieldReasoning, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(complaintverification.FieldVerifiedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(complaintverification.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{complaintverification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ComplaintVerificationUpdateOne is the builder for updating a single ComplaintVerification entity.
type ComplaintVerificationUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ComplaintVerificationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetComplaintAt sets the "complaint_at" field.
func (_u *ComplaintVerificationUpdateOne) SetComplaintAt(v time.Time) *ComplaintVerificationUpdateOne {
	_u.mutation.SetComplaintAt(v)
	return _u
}

// SetNillableComplaintAt sets the "complaint_at" field if the given value is not nil.
func (_u *ComplaintVerificationUpdateOne) SetNillableComplaintAt(v *time.Time) *ComplaintVerificationUpdateOne {
	if v != nil {
		_u.SetComplaintAt(*v)
	}
	return _u
}

// SetIsGenuine sets the "is_genuine" field.
func (_u *ComplaintVerificationUpdateOne) SetIsGenuine(v bool) *ComplaintVerificationUpdateOne {
	_u.mutation.SetIsGenuine(v)
	return _u
}

// SetNillableIsGenuine sets the "is_genuine" field if the given value is not nil.
func (_u *ComplaintVerificationUpdateOne) SetNillableIsGenuine(v *bool) *ComplaintVerificationUpdateOne {
	if v != nil {
		_u.SetIsGenuine(*v)
	}
	return _u
}

// SetReasoning sets the "reasoning" field.
func (_u *ComplaintVerificationUpdateOne) SetReasoning(v string) *ComplaintVerificationUpdateOne {
	_u.mutation.SetReasoning(v)
	return _u
}

// SetNillableReasoning sets the "reasoning" field if the given value is not nil.
func (_u *ComplaintVerificationUpdateOne) SetNillableReasoning(v *string) *ComplaintVerificationUpdateOne {
	if v != nil {
		_u.SetReasoning(*v)
	}
	return _u
}

// SetVerifiedAt sets the "verified_at" field.
func (_u *ComplaintVerificationUpdateOne) SetVerifiedAt(v time.Time) *ComplaintVerificationUpdateOne {
	_u.mutation.SetVerifiedAt(v)
	return _u
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *ComplaintVerificationUpdateOne) SetNillableVerifiedAt(v *time.Time) *ComplaintVerificationUpdateOne {
	if v != nil {
		_u.SetVerifiedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ComplaintVerificationUpdateOne) SetUpdatedAt(v time.Time) *ComplaintVerificationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ComplaintVerificationMutation object of the builder.
func (_u *ComplaintVerificationUpdateOne) Mutation() *ComplaintVerificationMutation {
	return _u.mutation
}

// Where appends a list predicates to the ComplaintVerificationUpdate builder.
func (_u *ComplaintVerificationUpdateOne) Where(ps ...predicate.ComplaintVerification) *ComplaintVerificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ComplaintVerificationUpdateOne) Select(field string, fields ...string) *ComplaintVerificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ComplaintVerification entity.
func (_u *ComplaintVerificationUpdateOne) Save(ctx context.Context) (*ComplaintVerification, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ComplaintVerificationUpdateOne) SaveX(ctx context.Context) *ComplaintVerification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ComplaintVerificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ComplaintVerificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ComplaintVerificationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := complaintverification.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ComplaintVerificationUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ComplaintVerificationUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ComplaintVerificationUpdateOne) sqlSave(ctx context.Context) (_node *ComplaintVerification, err error) {
	_spec := sqlgraph.NewUpdateSpec(complaintverification.Table, complaintverification.Columns, sqlgraph.NewFieldSpec(complaintverification.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ComplaintVerification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, complaintverification.FieldID)
		for _, f := range fields {
			if !complaintverification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != complaintverification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ComplaintAt(); ok {
		_spec.SetField(complaintverification.FieldComplaintAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsGenuine(); ok {
		_spec.SetField(complaintverification.FieldIsGenuine, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Reasoning(); ok {
		_spec.SetField(complaintverification.FieldReasoning, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(complaintverification.FieldVerifiedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(complaintverification.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ComplaintVerification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{complaintverification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
