// Code generated by ent, DO NOT EDIT.

package ent

import (
	"centropy-affilate/ent/complaintverification"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ComplaintVerification is the model entity for the ComplaintVerification schema.
type ComplaintVerification struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ExternalUserID holds the value of the "external_user_id" field.
	ExternalUserID uuid.UUID `json:"external_user_id,omitempty"`
	// ComplaintAt holds the value of the "complaint_at" field.
	ComplaintAt time.Time `json:"complaint_at,omitempty"`
	// IsGenuine holds the value of the "is_genuine" field.
	IsGenuine bool `json:"is_genuine,omitempty"`
	// Reasoning holds the value of the "reasoning" field.
	Reasoning string `json:"reasoning,omitempty"`
	// VerifiedAt holds the value of the "verified_at" field.
	VerifiedAt time.Time `json:"verified_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ComplaintVerification) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case complaintverification.FieldIsGenuine:
			values[i] = new(sql.NullBool)
		case complaintverification.FieldReasoning:
			values[i] = new(sql.NullString)
		case complaintverification.FieldComplaintAt, complaintverification.FieldVerifiedAt, complaintverification.FieldCreatedAt, complaintverification.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case complaintverification.FieldID, complaintverification.FieldExternalUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ComplaintVerification fields.
func (_m *ComplaintVerification) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case complaintverification.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case complaintverification.FieldExternalUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field external_user_id", values[i])
			} else if value != nil {
				_m.ExternalUserID = *value
			}
		case complaintverification.FieldComplaintAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field complaint_at", values[i])
			} else if value.Valid {
				_m.ComplaintAt = value.Time
			}
		case complaintverification.FieldIsGenuine:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_genuine", values[i])
			} else if value.Valid {
				_m.IsGenuine = value.Bool
			}
		case complaintverification.FieldReasoning:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reasoning", values[i])
			} else if value.Valid {
				_m.Reasoning = value.String
			}
		case complaintverification.FieldVerifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field verified_at", values[i])
			} else if value.Valid {
				_m.VerifiedAt = value.Time
			}
		case complaintverification.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case complaintverification.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ComplaintVerification.
// This includes values selected through modifiers, order, etc.
func (_m *ComplaintVerification) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ComplaintVerification.
// Note that you need to call ComplaintVerification.Unwrap() before calling this method if this ComplaintVerification
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ComplaintVerification) Update() *ComplaintVerificationUpdateOne {
	return NewComplaintVerificationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ComplaintVerification entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ComplaintVerification) Unwrap() *ComplaintVerification {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ComplaintVerification is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ComplaintVerification) String() string {
	var builder strings.Builder
	builder.WriteString("ComplaintVerification(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("external_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExternalUserID))
	builder.WriteString(", ")
	builder.WriteString("complaint_at=")
	builder.WriteString(_m.ComplaintAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_genuine=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsGenuine))
	builder.WriteString(", ")
	builder.WriteString("reasoning=")
	builder.WriteString(_m.Reasoning)
	builder.WriteString(", ")
	builder.WriteString("verified_at=")
	builder.WriteString(_m.VerifiedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ComplaintVerifications is a parsable slice of ComplaintVerification.
type ComplaintVerifications []*ComplaintVerification
