// Code generated by ent, DO NOT EDIT.

package ent

import (
	"centropy-affilate/ent/complaintverification"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ComplaintVerificationCreate is the builder for creating a ComplaintVerification entity.
type ComplaintVerificationCreate struct {
	config
	mutation *ComplaintVerificationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetExternalUserID sets the "external_user_id" field.
func (_c *ComplaintVerificationCreate) SetExternalUserID(v uuid.UUID) *ComplaintVerificationCreate {
	_c.mutation.SetExternalUserID(v)
	return _c
}

// SetComplaintAt sets the "complaint_at" field.
func (_c *ComplaintVerificationCreate) SetComplaintAt(v time.Time) *ComplaintVerificationCreate {
	_c.mutation.SetComplaintAt(v)
	return _c
}

// SetIsGenuine sets the "is_genuine" field.
func (_c *ComplaintVerificationCreate) SetIsGenuine(v bool) *ComplaintVerificationCreate {
	_c.mutation.SetIsGenuine(v)
	return _c
}

// SetReasoning sets the "reasoning" field.
func (_c *ComplaintVerificationCreate) SetReasoning(v string) *ComplaintVerificationCreate {
	_c.mutation.SetReasoning(v)
	return _c
}

// SetVerifiedAt sets the "verified_at" field.
func (_c *ComplaintVerificationCreate) SetVerifiedAt(v time.Time) *ComplaintVerificationCreate {
	_c.mutation.SetVerifiedAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ComplaintVerificationCreate) SetCreatedAt(v time.Time) *ComplaintVerificationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ComplaintVerificationCreate) SetNillableCreatedAt(v *time.Time) *ComplaintVerificationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ComplaintVerificationCreate) SetUpdatedAt(v time.Time) *ComplaintVerificationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ComplaintVerificationCreate) SetNillableUpdatedAt(v *time.Time) *ComplaintVerificationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ComplaintVerificationCreate) SetID(v uuid.UUID) *ComplaintVerificationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ComplaintVerificationCreate) SetNillableID(v *uuid.UUID) *ComplaintVerificationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ComplaintVerificationMutation object of the builder.
func (_c *ComplaintVerificationCreate) Mutation() *ComplaintVerificationMutation {
	return _c.mutation
}

// Save creates the ComplaintVerification in the database.
func (_c *ComplaintVerificationCreate) Save(ctx context.Context) (*ComplaintVerification, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ComplaintVerificationCreate) SaveX(ctx context.Context) *ComplaintVerification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ComplaintVerificationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ComplaintVerificationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ComplaintVerificationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := complaintverification.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := complaintverification.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := complaintverification.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ComplaintVerificationCreate) check() error {
	if _, ok := _c.mutation.ExternalUserID(); !ok {
		return &ValidationError{Name: "external_user_id", err: errors.New(`ent: missing required field "ComplaintVerification.external_user_id"`)}
	}
	if _, ok := _c.mutation.ComplaintAt(); !ok {
		return &ValidationError{Name: "complaint_at", err: errors.New(`ent: missing required field "ComplaintVerification.complaint_at"`)}
	}
	if _, ok := _c.mutation.IsGenuine(); !ok {
		return &ValidationError{Name: "is_genuine", err: errors.New(`ent: missing required field "ComplaintVerification.is_genuine"`)}
	}
	if _, ok := _c.mutation.Reasoning(); !ok {
		return &ValidationError{Name: "reasoning", err: errors.New(`ent: missing required field "ComplaintVerification.reasoning"`)}
	}
	if _, ok := _c.mutation.VerifiedAt(); !ok {
		return &ValidationError{Name: "verified_at", err: errors.New(`ent: missing required field "ComplaintVerification.verified_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ComplaintVerification.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ComplaintVerification.updated_at"`)}
	}
	return nil
}

func (_c *ComplaintVerificationCreate) sqlSave(ctx context.Context) (*ComplaintVerification, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ComplaintVerificationCreate) createSpec() (*ComplaintVerification, *sqlgraph.CreateSpec) {
	var (
		_node = &ComplaintVerification{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(complaintverification.Table, sqlgraph.NewFieldSpec(complaintverification.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ExternalUserID(); ok {
		_spec.SetField(complaintverification.FieldExternalUserID, field.TypeUUID, value)
		_node.ExternalUserID = value
	}
	if value, ok := _c.mutation.ComplaintAt(); ok {
		_spec.SetField(complaintverification.FieldComplaintAt, field.TypeTime, value)
		_node.ComplaintAt = value
	}
	if value, ok := _c.mutation.IsGenuine(); ok {
		_spec.SetField(complaintverification.FieldIsGenuine, field.TypeBool, value)
		_node.IsGenuine = value
	}
	if value, ok := _c.mutation.Reasoning(); ok {
		_spec.SetField(complaintverification.FieldReasoning, field.TypeString, value)
		_node.Reasoning = value
	}
	if value, ok := _c.mutation.VerifiedAt(); ok {
		_spec.SetField(complaintverification.FieldVerifiedAt, field.TypeTime, value)
		_node.VerifiedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(complaintverification.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(complaintverification.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ComplaintVerification.Create().
//		SetExternalUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ComplaintVerificationUpsert) {
//			SetExternalUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ComplaintVerificationCreate) OnConflict(opts ...sql.ConflictOption) *ComplaintVerificationUpsertOne {
	_c.conflict = opts
	return &ComplaintVerificationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ComplaintVerification.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ComplaintVerificationCreate) OnConflictColumns(columns ...string) *ComplaintVerificationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ComplaintVerificationUpsertOne{
		create: _c,
	}
}

type (
	// ComplaintVerificationUpsertOne is the builder for "upsert"-ing
	//  one ComplaintVerification node.
	ComplaintVerificationUpsertOne struct {
		create *ComplaintVerificationCreate
	}

	// ComplaintVerificationUpsert is the "OnConflict" setter.
	ComplaintVerificationUpsert struct {
		*sql.UpdateSet
	}
)

// SetComplaintAt sets the "complaint_at" field.
func (u *ComplaintVerificationUpsert) SetComplaintAt(v time.Time) *ComplaintVerificationUpsert {
	u.Set(complaintverification.FieldComplaintAt, v)
	return u
}

// UpdateComplaintAt sets the "complaint_at" field to the value that was provided on create.
func (u *ComplaintVerificationUpsert) UpdateComplaintAt() *ComplaintVerificationUpsert {
	u.SetExcluded(complaintverification.FieldComplaintAt)
	return u
}

// SetIsGenuine sets the "is_genuine" field.
func (u *ComplaintVerificationUpsert) SetIsGenuine(v bool) *ComplaintVerificationUpsert {
	u.Set(complaintverification.FieldIsGenuine, v)
	return u
}

// UpdateIsGenuine sets the "is_genuine" field to the value that was provided on create.
func (u *ComplaintVerificationUpsert) UpdateIsGenuine() *ComplaintVerificationUpsert {
	u.SetExcluded(complaintverification.FieldIsGenuine)
	return u
}

// SetReasoning sets the "reasoning" field.
func (u *ComplaintVerificationUpsert) SetReasoning(v string) *ComplaintVerificationUpsert {
	u.Set(complaintverification.FieldReasoning, v)
	return u
}

// UpdateReasoning sets the "reasoning" field to the value that was provided on create.
func (u *ComplaintVerificationUpsert) UpdateReasoning() *ComplaintVerificationUpsert {
	u.SetExcluded(complaintverification.FieldReasoning)
	return u
}

// SetVerifiedAt sets the "verified_at" field.
func (u *ComplaintVerificationUpsert) SetVerifiedAt(v time.Time) *ComplaintVerificationUpsert {
	u.Set(complaintverification.FieldVerifiedAt, v)
	return u
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *ComplaintVerificationUpsert) UpdateVerifiedAt() *ComplaintVerificationUpsert {
	u.SetExcluded(complaintverification.FieldVerifiedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ComplaintVerificationUpsert) SetUpdatedAt(v time.Time) *ComplaintVerificationUpsert {
	u.Set(complaintverification.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ComplaintVerificationUpsert) UpdateUpdatedAt() *ComplaintVerificationUpsert {
	u.SetExcluded(complaintverification.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ComplaintVerification.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(complaintverification.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ComplaintVerificationUpsertOne) UpdateNewValues() *ComplaintVerificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(complaintverification.FieldID)
		}
		if _, exists := u.create.mutation.ExternalUserID(); exists {
			s.SetIgnore(complaintverification.FieldExternalUserID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(complaintverification.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ComplaintVerification.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ComplaintVerificationUpsertOne) Ignore() *ComplaintVerificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ComplaintVerificationUpsertOne) DoNothing() *ComplaintVerificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ComplaintVerificationCreate.OnConflict
// documentation for more info.
func (u *ComplaintVerificationUpsertOne) Update(set func(*ComplaintVerificationUpsert)) *ComplaintVerificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ComplaintVerificationUpsert{UpdateSet: update})
	}))
	return u
}

// SetComplaintAt sets the "complaint_at" field.
func (u *ComplaintVerificationUpsertOne) SetComplaintAt(v time.Time) *ComplaintVerificationUpsertOne {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.SetComplaintAt(v)
	})
}

// UpdateComplaintAt sets the "complaint_at" field to the value that was provided on create.
func (u *ComplaintVerificationUpsertOne) UpdateComplaintAt() *ComplaintVerificationUpsertOne {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.UpdateComplaintAt()
	})
}

// SetIsGenuine sets the "is_genuine" field.
func (u *ComplaintVerificationUpsertOne) SetIsGenuine(v bool) *ComplaintVerificationUpsertOne {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.SetIsGenuine(v)
	})
}

// UpdateIsGenuine sets the "is_genuine" field to the value that was provided on create.
func (u *ComplaintVerificationUpsertOne) UpdateIsGenuine() *ComplaintVerificationUpsertOne {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.UpdateIsGenuine()
	})
}

// SetReasoning sets the "reasoning" field.
func (u *ComplaintVerificationUpsertOne) SetReasoning(v string) *ComplaintVerificationUpsertOne {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.SetReasoning(v)
	})
}

// UpdateReasoning sets the "reasoning" field to the value that was provided on create.
func (u *ComplaintVerificationUpsertOne) UpdateReasoning() *ComplaintVerificationUpsertOne {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.UpdateReasoning()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *ComplaintVerificationUpsertOne) SetVerifiedAt(v time.Time) *ComplaintVerificationUpsertOne {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *ComplaintVerificationUpsertOne) UpdateVerifiedAt() *ComplaintVerificationUpsertOne {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.UpdateVerifiedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ComplaintVerificationUpsertOne) SetUpdatedAt(v time.Time) *ComplaintVerificationUpsertOne {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ComplaintVerificationUpsertOne) UpdateUpdatedAt() *ComplaintVerificationUpsertOne {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ComplaintVerificationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ComplaintVerificationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ComplaintVerificationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ComplaintVerificationUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ComplaintVerificationUpsertOne.ID is not supported by MySQL driver. Use ComplaintVerificationUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ComplaintVerificationUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ComplaintVerificationCreateBulk is the builder for creating many ComplaintVerification entities in bulk.
type ComplaintVerificationCreateBulk struct {
	config
	err      error
	builders []*ComplaintVerificationCreate
	conflict []sql.ConflictOption
}

// Save creates the ComplaintVerification entities in the database.
func (_c *ComplaintVerificationCreateBulk) Save(ctx context.Context) ([]*ComplaintVerification, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ComplaintVerification, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ComplaintVerificationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ComplaintVerificationCreateBulk) SaveX(ctx context.Context) []*ComplaintVerification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ComplaintVerificationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ComplaintVerificationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ComplaintVerification.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ComplaintVerificationUpsert) {
//			SetExternalUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ComplaintVerificationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ComplaintVerificationUpsertBulk {
	_c.conflict = opts
	return &ComplaintVerificationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ComplaintVerification.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ComplaintVerificationCreateBulk) OnConflictColumns(columns ...string) *ComplaintVerificationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ComplaintVerificationUpsertBulk{
		create: _c,
	}
}

// ComplaintVerificationUpsertBulk is the builder for "upsert"-ing
// a bulk of ComplaintVerification nodes.
type ComplaintVerificationUpsertBulk struct {
	create *ComplaintVerificationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ComplaintVerification.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(complaintverification.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ComplaintVerificationUpsertBulk) UpdateNewValues() *ComplaintVerificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(complaintverification.FieldID)
			}
			if _, exists := b.mutation.ExternalUserID(); exists {
				s.SetIgnore(complaintverification.FieldExternalUserID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(complaintverification.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ComplaintVerification.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ComplaintVerificationUpsertBulk) Ignore() *ComplaintVerificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ComplaintVerificationUpsertBulk) DoNothing() *ComplaintVerificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ComplaintVerificationCreateBulk.OnConflict
// documentation for more info.
func (u *ComplaintVerificationUpsertBulk) Update(set func(*ComplaintVerificationUpsert)) *ComplaintVerificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ComplaintVerificationUpsert{UpdateSet: update})
	}))
	return u
}

// SetComplaintAt sets the "complaint_at" field.
func (u *ComplaintVerificationUpsertBulk) SetComplaintAt(v time.Time) *ComplaintVerificationUpsertBulk {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.SetComplaintAt(v)
	})
}

// UpdateComplaintAt sets the "complaint_at" field to the value that was provided on create.
func (u *ComplaintVerificationUpsertBulk) UpdateComplaintAt() *ComplaintVerificationUpsertBulk {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.UpdateComplaintAt()
	})
}

// SetIsGenuine sets the "is_genuine" field.
func (u *ComplaintVerificationUpsertBulk) SetIsGenuine(v bool) *ComplaintVerificationUpsertBulk {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.SetIsGenuine(v)
	})
}

// UpdateIsGenuine sets the "is_genuine" field to the value that was provided on create.
func (u *ComplaintVerificationUpsertBulk) UpdateIsGenuine() *ComplaintVerificationUpsertBulk {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.UpdateIsGenuine()
	})
}

// SetReasoning sets the "reasoning" field.
func (u *ComplaintVerificationUpsertBulk) SetReasoning(v string) *ComplaintVerificationUpsertBulk {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.SetReasoning(v)
	})
}

// UpdateReasoning sets the "reasoning" field to the value that was provided on create.
func (u *ComplaintVerificationUpsertBulk) UpdateReasoning() *ComplaintVerificationUpsertBulk {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.UpdateReasoning()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *ComplaintVerificationUpsertBulk) SetVerifiedAt(v time.Time) *ComplaintVerificationUpsertBulk {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *ComplaintVerificationUpsertBulk) UpdateVerifiedAt() *ComplaintVerificationUpsertBulk {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.UpdateVerifiedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ComplaintVerificationUpsertBulk) SetUpdatedAt(v time.Time) *ComplaintVerificationUpsertBulk {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ComplaintVerificationUpsertBulk) UpdateUpdatedAt() *ComplaintVerificationUpsertBulk {
	return u.Update(func(s *ComplaintVerificationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ComplaintVerificationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ComplaintVerificationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ComplaintVerificationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ComplaintVerificationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
