// Code generated by ent, DO NOT EDIT.

package ent

import (
	"centropy-affilate/ent/customeranalysis"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// CustomerAnalysis is the model entity for the CustomerAnalysis schema.
type CustomerAnalysis struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ExternalUserID holds the value of the "external_user_id" field.
	ExternalUserID uuid.UUID `json:"external_user_id,omitempty"`
	// Category holds the value of the "category" field.
	Category customeranalysis.Category `json:"category,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// Confidence holds the value of the "confidence" field.
	Confidence customeranalysis.Confidence `json:"confidence,omitempty"`
	// LastMessageAt holds the value of the "last_message_at" field.
	LastMessageAt *time.Time `json:"last_message_at,omitempty"`
	// AnalyzedAt holds the value of the "analyzed_at" field.
	AnalyzedAt time.Time `json:"analyzed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CustomerAnalysis) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case customeranalysis.FieldCategory, customeranalysis.FieldSummary, customeranalysis.FieldConfidence:
			values[i] = new(sql.NullString)
		case customeranalysis.FieldLastMessageAt, customeranalysis.FieldAnalyzedAt, customeranalysis.FieldCreatedAt, customeranalysis.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case customeranalysis.FieldID, customeranalysis.FieldExternalUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CustomerAnalysis fields.
func (_m *CustomerAnalysis) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case customeranalysis.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case customeranalysis.FieldExternalUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field external_user_id", values[i])
			} else if value != nil {
				_m.ExternalUserID = *value
			}
		case customeranalysis.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = customeranalysis.Category(value.String)
			}
		case customeranalysis.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case customeranalysis.FieldConfidence:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field confidence", values[i])
			} else if value.Valid {
				_m.Confidence = customeranalysis.Confidence(value.String)
			}
		case customeranalysis.FieldLastMessageAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_message_at", values[i])
			} else if value.Valid {
				_m.LastMessageAt = new(time.Time)
				*_m.LastMessageAt = value.Time
			}
		case customeranalysis.FieldAnalyzedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field analyzed_at", values[i])
			} else if value.Valid {
				_m.AnalyzedAt = value.Time
			}
		case customeranalysis.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case customeranalysis.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CustomerAnalysis.
// This includes values selected through modifiers, order, etc.
func (_m *CustomerAnalysis) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CustomerAnalysis.
// Note that you need to call CustomerAnalysis.Unwrap() before calling this method if this CustomerAnalysis
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CustomerAnalysis) Update() *CustomerAnalysisUpdateOne {
	return NewCustomerAnalysisClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CustomerAnalysis entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CustomerAnalysis) Unwrap() *CustomerAnalysis {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CustomerAnalysis is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CustomerAnalysis) String() string {
	var builder strings.Builder
	builder.WriteString("CustomerAnalysis(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("external_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExternalUserID))
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(fmt.Sprintf("%v", _m.Category))
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("confidence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Confidence))
	builder.WriteString(", ")
	if v := _m.LastMessageAt; v != nil {
		builder.WriteString("last_message_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("analyzed_at=")
	builder.WriteString(_m.AnalyzedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CustomerAnalyses is a parsable slice of CustomerAnalysis.
type CustomerAnalyses []*CustomerAnalysis
