// Code generated by ent, DO NOT EDIT.

package ent

import (
	"centropy-affilate/ent/customeranalysis"
	"centropy-affilate/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CustomerAnalysisDelete is the builder for deleting a CustomerAnalysis entity.
type CustomerAnalysisDelete struct {
	config
	hooks    []Hook
	mutation *CustomerAnalysisMutation
}

// Where appends a list predicates to the CustomerAnalysisDelete builder.
func (_d *CustomerAnalysisDelete) Where(ps ...predicate.CustomerAnalysis) *CustomerAnalysisDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CustomerAnalysisDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CustomerAnalysisDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CustomerAnalysisDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(customeranalysis.Table, sqlgraph.NewFieldSpec(customeranalysis.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CustomerAnalysisDeleteOne is the builder for deleting a single CustomerAnalysis entity.
type CustomerAnalysisDeleteOne struct {
	_d *CustomerAnalysisDelete
}

// Where appends a list predicates to the CustomerAnalysisDelete builder.
func (_d *CustomerAnalysisDeleteOne) Where(ps ...predicate.CustomerAnalysis) *CustomerAnalysisDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CustomerAnalysisDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{customeranalysis.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CustomerAnalysisDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
