// Code generated by ent, DO NOT EDIT.

package ent

import (
	"centropy-affilate/ent/customeranalysis"
	"centropy-affilate/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CustomerAnalysisUpdate is the builder for updating CustomerAnalysis entities.
type CustomerAnalysisUpdate struct {
	config
	hooks     []Hook
	mutation  *CustomerAnalysisMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CustomerAnalysisUpdate builder.
func (_u *CustomerAnalysisUpdate) Where(ps ...predicate.CustomerAnalysis) *CustomerAnalysisUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCategory sets the "category" field.
func (_u *CustomerAnalysisUpdate) SetCategory(v customeranalysis.Category) *CustomerAnalysisUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *CustomerAnalysisUpdate) SetNillableCategory(v *customeranalysis.Category) *CustomerAnalysisUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *CustomerAnalysisUpdate) SetSummary(v string) *CustomerAnalysisUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *CustomerAnalysisUpdate) SetNillableSummary(v *string) *CustomerAnalysisUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *CustomerAnalysisUpdate) SetConfidence(v customeranalysis.Confidence) *CustomerAnalysisUpdate {
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *CustomerAnalysisUpdate) SetNillableConfidence(v *customeranalysis.Confidence) *CustomerAnalysisUpdate {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *CustomerAnalysisUpdate) SetLastMessageAt(v time.Time) *CustomerAnalysisUpdate {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *CustomerAnalysisUpdate) SetNillableLastMessageAt(v *time.Time) *CustomerAnalysisUpdate {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (_u *CustomerAnalysisUpdate) ClearLastMessageAt() *CustomerAnalysisUpdate {
	_u.mutation.ClearLastMessageAt()
	return _u
}

// SetAnalyzedAt sets the "analyzed_at" field.
func (_u *CustomerAnalysisUpdate) SetAnalyzedAt(v time.Time) *CustomerAnalysisUpdate {
	_u.mutation.SetAnalyzedAt(v)
	return _u
}

// SetNillableAnalyzedAt sets the "analyzed_at" field if the given value is not nil.
func (_u *CustomerAnalysisUpdate) SetNillableAnalyzedAt(v *time.Time) *CustomerAnalysisUpdate {
	if v != nil {
		_u.SetAnalyzedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomerAnalysisUpdate) SetUpdatedAt(v time.Time) *CustomerAnalysisUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CustomerAnalysisMutation object of the builder.
func (_u *CustomerAnalysisUpdate) Mutation() *CustomerAnalysisMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CustomerAnalysisUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomerAnalysisUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CustomerAnalysisUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomerAnalysisUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomerAnalysisUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := customeranalysis.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomerAnalysisUpdate) check() error {
	if v, ok := _u.mutation.Category(); ok {
		if err := customeranalysis.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "CustomerAnalysis.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Confidence(); ok {
		if err := customeranalysis.ConfidenceValidator(v); err != nil {
			return &ValidationError{Name: "confidence", err: fmt.Errorf(`ent: validator failed for field "CustomerAnalysis.confidence": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CustomerAnalysisUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CustomerAnalysisUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CustomerAnalysisUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(customeranalysis.Table, customeranalysis.Columns, sqlgraph.NewFieldSpec(customeranalysis.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(customeranalysis.FieldCategory, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(customeranalysis.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(customeranalysis.FieldConfidence, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(customeranalysis.FieldLastMessageAt, field.TypeTime, value)
	}
	if _u.mutation.LastMessageAtCleared() {
		_spec.ClearField(customeranalysis.FieldLastMessageAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AnalyzedAt(); ok {
		_spec.SetField(customeranalysis.FieldAnalyzedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(customeranalysis.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customeranalysis.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CustomerAnalysisUpdateOne is the builder for updating a single CustomerAnalysis entity.
type CustomerAnalysisUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CustomerAnalysisMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCategory sets the "category" field.
func (_u *CustomerAnalysisUpdateOne) SetCategory(v customeranalysis.Category) *CustomerAnalysisUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *CustomerAnalysisUpdateOne) SetNillableCategory(v *customeranalysis.Category) *CustomerAnalysisUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *CustomerAnalysisUpdateOne) SetSummary(v string) *CustomerAnalysisUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *CustomerAnalysisUpdateOne) SetNillableSummary(v *string) *CustomerAnalysisUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *CustomerAnalysisUpdateOne) SetConfidence(v customeranalysis.Confidence) *CustomerAnalysisUpdateOne {
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *CustomerAnalysisUpdateOne) SetNillableConfidence(v *customeranalysis.Confidence) *CustomerAnalysisUpdateOne {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// SetLastMessageAt sets the "last_message_at" field.
func (_u *CustomerAnalysisUpdateOne) SetLastMessageAt(v time.Time) *CustomerAnalysisUpdateOne {
	_u.mutation.SetLastMessageAt(v)
	return _u
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_u *CustomerAnalysisUpdateOne) SetNillableLastMessageAt(v *time.Time) *CustomerAnalysisUpdateOne {
	if v != nil {
		_u.SetLastMessageAt(*v)
	}
	return _u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (_u *CustomerAnalysisUpdateOne) ClearLastMessageAt() *CustomerAnalysisUpdateOne {
	_u.mutation.ClearLastMessageAt()
	return _u
}

// SetAnalyzedAt sets the "analyzed_at" field.
func (_u *CustomerAnalysisUpdateOne) SetAnalyzedAt(v time.Time) *CustomerAnalysisUpdateOne {
	_u.mutation.SetAnalyzedAt(v)
	return _u
}

// SetNillableAnalyzedAt sets the "analyzed_at" field if the given value is not nil.
func (_u *CustomerAnalysisUpdateOne) SetNillableAnalyzedAt(v *time.Time) *CustomerAnalysisUpdateOne {
	if v != nil {
		_u.SetAnalyzedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomerAnalysisUpdateOne) SetUpdatedAt(v time.Time) *CustomerAnalysisUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CustomerAnalysisMutation object of the builder.
func (_u *CustomerAnalysisUpdateOne) Mutation() *CustomerAnalysisMutation {
	return _u.mutation
}

// Where appends a list predicates to the CustomerAnalysisUpdate builder.
func (_u *CustomerAnalysisUpdateOne) Where(ps ...predicate.CustomerAnalysis) *CustomerAnalysisUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CustomerAnalysisUpdateOne) Select(field string, fields ...string) *CustomerAnalysisUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CustomerAnalysis entity.
func (_u *CustomerAnalysisUpdateOne) Save(ctx context.Context) (*CustomerAnalysis, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomerAnalysisUpdateOne) SaveX(ctx context.Context) *CustomerAnalysis {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CustomerAnalysisUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomerAnalysisUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomerAnalysisUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := customeranalysis.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomerAnalysisUpdateOne) check() error {
	if v, ok := _u.mutation.Category(); ok {
		if err := customeranalysis.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "CustomerAnalysis.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Confidence(); ok {
		if err := customeranalysis.ConfidenceValidator(v); err != nil {
			return &ValidationError{Name: "confidence", err: fmt.Errorf(`ent: validator failed for field "CustomerAnalysis.confidence": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CustomerAnalysisUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CustomerAnalysisUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CustomerAnalysisUpdateOne) sqlSave(ctx context.Context) (_node *CustomerAnalysis, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(customeranalysis.Table, customeranalysis.Columns, sqlgraph.NewFieldSpec(customeranalysis.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CustomerAnalysis.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, customeranalysis.FieldID)
		for _, f := range fields {
			if !customeranalysis.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != customeranalysis.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(customeranalysis.FieldCategory, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(customeranalysis.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(customeranalysis.FieldConfidence, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastMessageAt(); ok {
		_spec.SetField(customeranalysis.FieldLastMessageAt, field.TypeTime, value)
	}
	if _u.mutation.LastMessageAtCleared() {
		_spec.ClearField(customeranalysis.FieldLastMessageAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AnalyzedAt(); ok {
		_spec.SetField(customeranalysis.FieldAnalyzedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(customeranalysis.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &CustomerAnalysis{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customeranalysis.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
