// Code generated by ent, DO NOT EDIT.

package ent

import (
	"centropy-affilate/ent/customeranalysis"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CustomerAnalysisCreate is the builder for creating a CustomerAnalysis entity.
type CustomerAnalysisCreate struct {
	config
	mutation *CustomerAnalysisMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetExternalUserID sets the "external_user_id" field.
func (_c *CustomerAnalysisCreate) SetExternalUserID(v uuid.UUID) *CustomerAnalysisCreate {
	_c.mutation.SetExternalUserID(v)
	return _c
}

// SetCategory sets the "category" field.
func (_c *CustomerAnalysisCreate) SetCategory(v customeranalysis.Category) *CustomerAnalysisCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *CustomerAnalysisCreate) SetSummary(v string) *CustomerAnalysisCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetConfidence sets the "confidence" field.
func (_c *CustomerAnalysisCreate) SetConfidence(v customeranalysis.Confidence) *CustomerAnalysisCreate {
	_c.mutation.SetConfidence(v)
	return _c
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_c *CustomerAnalysisCreate) SetNillableConfidence(v *customeranalysis.Confidence) *CustomerAnalysisCreate {
	if v != nil {
		_c.SetConfidence(*v)
	}
	return _c
}

// SetLastMessageAt sets the "last_message_at" field.
func (_c *CustomerAnalysisCreate) SetLastMessageAt(v time.Time) *CustomerAnalysisCreate {
	_c.mutation.SetLastMessageAt(v)
	return _c
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_c *CustomerAnalysisCreate) SetNillableLastMessageAt(v *time.Time) *CustomerAnalysisCreate {
	if v != nil {
		_c.SetLastMessageAt(*v)
	}
	return _c
}

// SetAnalyzedAt sets the "analyzed_at" field.
func (_c *CustomerAnalysisCreate) SetAnalyzedAt(v time.Time) *CustomerAnalysisCreate {
	_c.mutation.SetAnalyzedAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CustomerAnalysisCreate) SetCreatedAt(v time.Time) *CustomerAnalysisCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CustomerAnalysisCreate) SetNillableCreatedAt(v *time.Time) *CustomerAnalysisCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CustomerAnalysisCreate) SetUpdatedAt(v time.Time) *CustomerAnalysisCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CustomerAnalysisCreate) SetNillableUpdatedAt(v *time.Time) *CustomerAnalysisCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CustomerAnalysisCreate) SetID(v uuid.UUID) *CustomerAnalysisCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CustomerAnalysisCreate) SetNillableID(v *uuid.UUID) *CustomerAnalysisCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the CustomerAnalysisMutation object of the builder.
func (_c *CustomerAnalysisCreate) Mutation() *CustomerAnalysisMutation {
	return _c.mutation
}

// Save creates the CustomerAnalysis in the database.
func (_c *CustomerAnalysisCreate) Save(ctx context.Context) (*CustomerAnalysis, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CustomerAnalysisCreate) SaveX(ctx context.Context) *CustomerAnalysis {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomerAnalysisCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomerAnalysisCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CustomerAnalysisCreate) defaults() {
	if _, ok := _c.mutation.Confidence(); !ok {
		v := customeranalysis.DefaultConfidence
		_c.mutation.SetConfidence(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := customeranalysis.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := customeranalysis.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := customeranalysis.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CustomerAnalysisCreate) check() error {
	if _, ok := _c.mutation.ExternalUserID(); !ok {
		return &ValidationError{Name: "external_user_id", err: errors.New(`ent: missing required field "CustomerAnalysis.external_user_id"`)}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "CustomerAnalysis.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := customeranalysis.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "CustomerAnalysis.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "CustomerAnalysis.summary"`)}
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		return &ValidationError{Name: "confidence", err: errors.New(`ent: missing required field "CustomerAnalysis.confidence"`)}
	}
	if v, ok := _c.mutation.Confidence(); ok {
		if err := customeranalysis.ConfidenceValidator(v); err != nil {
			return &ValidationError{Name: "confidence", err: fmt.Errorf(`ent: validator failed for field "CustomerAnalysis.confidence": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AnalyzedAt(); !ok {
		return &ValidationError{Name: "analyzed_at", err: errors.New(`ent: missing required field "CustomerAnalysis.analyzed_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CustomerAnalysis.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CustomerAnalysis.updated_at"`)}
	}
	return nil
}

func (_c *CustomerAnalysisCreate) sqlSave(ctx context.Context) (*CustomerAnalysis, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CustomerAnalysisCreate) createSpec() (*CustomerAnalysis, *sqlgraph.CreateSpec) {
	var (
		_node = &CustomerAnalysis{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(customeranalysis.Table, sqlgraph.NewFieldSpec(customeranalysis.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ExternalUserID(); ok {
		_spec.SetField(customeranalysis.FieldExternalUserID, field.TypeUUID, value)
		_node.ExternalUserID = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(customeranalysis.FieldCategory, field.TypeEnum, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(customeranalysis.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.Confidence(); ok {
		_spec.SetField(customeranalysis.FieldConfidence, field.TypeEnum, value)
		_node.Confidence = value
	}
	if value, ok := _c.mutation.LastMessageAt(); ok {
		_spec.SetField(customeranalysis.FieldLastMessageAt, field.TypeTime, value)
		_node.LastMessageAt = &value
	}
	if value, ok := _c.mutation.AnalyzedAt(); ok {
		_spec.SetField(customeranalysis.FieldAnalyzedAt, field.TypeTime, value)
		_node.AnalyzedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(customeranalysis.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(customeranalysis.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomerAnalysis.Create().
//		SetExternalUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomerAnalysisUpsert) {
//			SetExternalUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomerAnalysisCreate) OnConflict(opts ...sql.ConflictOption) *CustomerAnalysisUpsertOne {
	_c.conflict = opts
	return &CustomerAnalysisUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomerAnalysis.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomerAnalysisCreate) OnConflictColumns(columns ...string) *CustomerAnalysisUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomerAnalysisUpsertOne{
		create: _c,
	}
}

type (
	// CustomerAnalysisUpsertOne is the builder for "upsert"-ing
	//  one CustomerAnalysis node.
	CustomerAnalysisUpsertOne struct {
		create *CustomerAnalysisCreate
	}

	// CustomerAnalysisUpsert is the "OnConflict" setter.
	CustomerAnalysisUpsert struct {
		*sql.UpdateSet
	}
)

// SetCategory sets the "category" field.
func (u *CustomerAnalysisUpsert) SetCategory(v customeranalysis.Category) *CustomerAnalysisUpsert {
	u.Set(customeranalysis.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *CustomerAnalysisUpsert) UpdateCategory() *CustomerAnalysisUpsert {
	u.SetExcluded(customeranalysis.FieldCategory)
	return u
}

// SetSummary sets the "summary" field.
func (u *CustomerAnalysisUpsert) SetSummary(v string) *CustomerAnalysisUpsert {
	u.Set(customeranalysis.FieldSummary, v)
	return u
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *CustomerAnalysisUpsert) UpdateSummary() *CustomerAnalysisUpsert {
	u.SetExcluded(customeranalysis.FieldSummary)
	return u
}

// SetConfidence sets the "confidence" field.
func (u *CustomerAnalysisUpsert) SetConfidence(v customeranalysis.Confidence) *CustomerAnalysisUpsert {
	u.Set(customeranalysis.FieldConfidence, v)
	return u
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *CustomerAnalysisUpsert) UpdateConfidence() *CustomerAnalysisUpsert {
	u.SetExcluded(customeranalysis.FieldConfidence)
	return u
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *CustomerAnalysisUpsert) SetLastMessageAt(v time.Time) *CustomerAnalysisUpsert {
	u.Set(customeranalysis.FieldLastMessageAt, v)
	return u
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *CustomerAnalysisUpsert) UpdateLastMessageAt() *CustomerAnalysisUpsert {
	u.SetExcluded(customeranalysis.FieldLastMessageAt)
	return u
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *CustomerAnalysisUpsert) ClearLastMessageAt() *CustomerAnalysisUpsert {
	u.SetNull(customeranalysis.FieldLastMessageAt)
	return u
}

// SetAnalyzedAt sets the "analyzed_at" field.
func (u *CustomerAnalysisUpsert) SetAnalyzedAt(v time.Time) *CustomerAnalysisUpsert {
	u.Set(customeranalysis.FieldAnalyzedAt, v)
	return u
}

// UpdateAnalyzedAt sets the "analyzed_at" field to the value that was provided on create.
func (u *CustomerAnalysisUpsert) UpdateAnalyzedAt() *CustomerAnalysisUpsert {
	u.SetExcluded(customeranalysis.FieldAnalyzedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomerAnalysisUpsert) SetUpdatedAt(v time.Time) *CustomerAnalysisUpsert {
	u.Set(customeranalysis.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomerAnalysisUpsert) UpdateUpdatedAt() *CustomerAnalysisUpsert {
	u.SetExcluded(customeranalysis.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CustomerAnalysis.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(customeranalysis.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CustomerAnalysisUpsertOne) UpdateNewValues() *CustomerAnalysisUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(customeranalysis.FieldID)
		}
		if _, exists := u.create.mutation.ExternalUserID(); exists {
			s.SetIgnore(customeranalysis.FieldExternalUserID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(customeranalysis.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomerAnalysis.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CustomerAnalysisUpsertOne) Ignore() *CustomerAnalysisUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomerAnalysisUpsertOne) DoNothing() *CustomerAnalysisUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomerAnalysisCreate.OnConflict
// documentation for more info.
func (u *CustomerAnalysisUpsertOne) Update(set func(*CustomerAnalysisUpsert)) *CustomerAnalysisUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomerAnalysisUpsert{UpdateSet: update})
	}))
	return u
}

// SetCategory sets the "category" field.
func (u *CustomerAnalysisUpsertOne) SetCategory(v customeranalysis.Category) *CustomerAnalysisUpsertOne {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *CustomerAnalysisUpsertOne) UpdateCategory() *CustomerAnalysisUpsertOne {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.UpdateCategory()
	})
}

// SetSummary sets the "summary" field.
func (u *CustomerAnalysisUpsertOne) SetSummary(v string) *CustomerAnalysisUpsertOne {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *CustomerAnalysisUpsertOne) UpdateSummary() *CustomerAnalysisUpsertOne {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.UpdateSummary()
	})
}

// SetConfidence sets the "confidence" field.
func (u *CustomerAnalysisUpsertOne) SetConfidence(v customeranalysis.Confidence) *CustomerAnalysisUpsertOne {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.SetConfidence(v)
	})
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *CustomerAnalysisUpsertOne) UpdateConfidence() *CustomerAnalysisUpsertOne {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.UpdateConfidence()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *CustomerAnalysisUpsertOne) SetLastMessageAt(v time.Time) *CustomerAnalysisUpsertOne {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *CustomerAnalysisUpsertOne) UpdateLastMessageAt() *CustomerAnalysisUpsertOne {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.UpdateLastMessageAt()
	})
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *CustomerAnalysisUpsertOne) ClearLastMessageAt() *CustomerAnalysisUpsertOne {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.ClearLastMessageAt()
	})
}

// SetAnalyzedAt sets the "analyzed_at" field.
func (u *CustomerAnalysisUpsertOne) SetAnalyzedAt(v time.Time) *CustomerAnalysisUpsertOne {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.SetAnalyzedAt(v)
	})
}

// UpdateAnalyzedAt sets the "analyzed_at" field to the value that was provided on create.
func (u *CustomerAnalysisUpsertOne) UpdateAnalyzedAt() *CustomerAnalysisUpsertOne {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.UpdateAnalyzedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomerAnalysisUpsertOne) SetUpdatedAt(v time.Time) *CustomerAnalysisUpsertOne {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomerAnalysisUpsertOne) UpdateUpdatedAt() *CustomerAnalysisUpsertOne {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CustomerAnalysisUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomerAnalysisCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomerAnalysisUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CustomerAnalysisUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CustomerAnalysisUpsertOne.ID is not supported by MySQL driver. Use CustomerAnalysisUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CustomerAnalysisUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CustomerAnalysisCreateBulk is the builder for creating many CustomerAnalysis entities in bulk.
type CustomerAnalysisCreateBulk struct {
	config
	err      error
	builders []*CustomerAnalysisCreate
	conflict []sql.ConflictOption
}

// Save creates the CustomerAnalysis entities in the database.
func (_c *CustomerAnalysisCreateBulk) Save(ctx context.Context) ([]*CustomerAnalysis, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CustomerAnalysis, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomerAnalysisMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CustomerAnalysisCreateBulk) SaveX(ctx context.Context) []*CustomerAnalysis {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomerAnalysisCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomerAnalysisCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomerAnalysis.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomerAnalysisUpsert) {
//			SetExternalUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomerAnalysisCreateBulk) OnConflict(opts ...sql.ConflictOption) *CustomerAnalysisUpsertBulk {
	_c.conflict = opts
	return &CustomerAnalysisUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomerAnalysis.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomerAnalysisCreateBulk) OnConflictColumns(columns ...string) *CustomerAnalysisUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomerAnalysisUpsertBulk{
		create: _c,
	}
}

// CustomerAnalysisUpsertBulk is the builder for "upsert"-ing
// a bulk of CustomerAnalysis nodes.
type CustomerAnalysisUpsertBulk struct {
	create *CustomerAnalysisCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CustomerAnalysis.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(customeranalysis.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CustomerAnalysisUpsertBulk) UpdateNewValues() *CustomerAnalysisUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(customeranalysis.FieldID)
			}
			if _, exists := b.mutation.ExternalUserID(); exists {
				s.SetIgnore(customeranalysis.FieldExternalUserID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(customeranalysis.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomerAnalysis.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CustomerAnalysisUpsertBulk) Ignore() *CustomerAnalysisUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomerAnalysisUpsertBulk) DoNothing() *CustomerAnalysisUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomerAnalysisCreateBulk.OnConflict
// documentation for more info.
func (u *CustomerAnalysisUpsertBulk) Update(set func(*CustomerAnalysisUpsert)) *CustomerAnalysisUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomerAnalysisUpsert{UpdateSet: update})
	}))
	return u
}

// SetCategory sets the "category" field.
func (u *CustomerAnalysisUpsertBulk) SetCategory(v customeranalysis.Category) *CustomerAnalysisUpsertBulk {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *CustomerAnalysisUpsertBulk) UpdateCategory() *CustomerAnalysisUpsertBulk {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.UpdateCategory()
	})
}

// SetSummary sets the "summary" field.
func (u *CustomerAnalysisUpsertBulk) SetSummary(v string) *CustomerAnalysisUpsertBulk {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *CustomerAnalysisUpsertBulk) UpdateSummary() *CustomerAnalysisUpsertBulk {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.UpdateSummary()
	})
}

// SetConfidence sets the "confidence" field.
func (u *CustomerAnalysisUpsertBulk) SetConfidence(v customeranalysis.Confidence) *CustomerAnalysisUpsertBulk {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.SetConfidence(v)
	})
}

// UpdateConfidence sets the "confidence" field to the value that was provided on create.
func (u *CustomerAnalysisUpsertBulk) UpdateConfidence() *CustomerAnalysisUpsertBulk {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.UpdateConfidence()
	})
}

// SetLastMessageAt sets the "last_message_at" field.
func (u *CustomerAnalysisUpsertBulk) SetLastMessageAt(v time.Time) *CustomerAnalysisUpsertBulk {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.SetLastMessageAt(v)
	})
}

// UpdateLastMessageAt sets the "last_message_at" field to the value that was provided on create.
func (u *CustomerAnalysisUpsertBulk) UpdateLastMessageAt() *CustomerAnalysisUpsertBulk {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.UpdateLastMessageAt()
	})
}

// ClearLastMessageAt clears the value of the "last_message_at" field.
func (u *CustomerAnalysisUpsertBulk) ClearLastMessageAt() *CustomerAnalysisUpsertBulk {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.ClearLastMessageAt()
	})
}

// SetAnalyzedAt sets the "analyzed_at" field.
func (u *CustomerAnalysisUpsertBulk) SetAnalyzedAt(v time.Time) *CustomerAnalysisUpsertBulk {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.SetAnalyzedAt(v)
	})
}

// UpdateAnalyzedAt sets the "analyzed_at" field to the value that was provided on create.
func (u *CustomerAnalysisUpsertBulk) UpdateAnalyzedAt() *CustomerAnalysisUpsertBulk {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.UpdateAnalyzedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomerAnalysisUpsertBulk) SetUpdatedAt(v time.Time) *CustomerAnalysisUpsertBulk {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomerAnalysisUpsertBulk) UpdateUpdatedAt() *CustomerAnalysisUpsertBulk {
	return u.Update(func(s *CustomerAnalysisUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CustomerAnalysisUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CustomerAnalysisCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomerAnalysisCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomerAnalysisUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
