// Code generated by ent, DO NOT EDIT.

package ent

import (
	"centropy-affilate/ent/adminuser"
	"centropy-affilate/ent/complaintverification"
	"centropy-affilate/ent/customer"
	"centropy-affilate/ent/customeranalysis"
	"centropy-affilate/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminuserFields := schema.AdminUser{}.Fields()
	_ = adminuserFields
	// adminuserDescEmail is the schema descriptor for email field.
	adminuserDescEmail := adminuserFields[1].Descriptor()
	// adminuser.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	adminuser.EmailValidator = func() func(string) error {
		validators := adminuserDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// adminuserDescPasswordHash is the schema descriptor for password_hash field.
	adminuserDescPasswordHash := adminuserFields[2].Descriptor()
	// adminuser.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	adminuser.PasswordHashValidator = adminuserDescPasswordHash.Validators[0].(func(string) error)
	// adminuserDescName is the schema descriptor for name field.
	adminuserDescName := adminuserFields[3].Descriptor()
	// adminuser.NameValidator is a validator for the "name" field. It is called by the builders before save.
	adminuser.NameValidator = adminuserDescName.Validators[0].(func(string) error)
	// adminuserDescCreatedAt is the schema descriptor for created_at field.
	adminuserDescCreatedAt := adminuserFields[4].Descriptor()
	// adminuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminuser.DefaultCreatedAt = adminuserDescCreatedAt.Default.(func() time.Time)
	// adminuserDescUpdatedAt is the schema descriptor for updated_at field.
	adminuserDescUpdatedAt := adminuserFields[5].Descriptor()
	// adminuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	adminuser.DefaultUpdatedAt = adminuserDescUpdatedAt.Default.(func() time.Time)
	// adminuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	adminuser.UpdateDefaultUpdatedAt = adminuserDescUpdatedAt.UpdateDefault.(func() time.Time)
	// adminuserDescID is the schema descriptor for id field.
	adminuserDescID := adminuserFields[0].Descriptor()
	// adminuser.DefaultID holds the default value on creation for the id field.
	adminuser.DefaultID = adminuserDescID.Default.(func() uuid.UUID)
	complaintverificationFields := schema.ComplaintVerification{}.Fields()
	_ = complaintverificationFields
	// complaintverificationDescCreatedAt is the schema descriptor for created_at field.
	complaintverificationDescCreatedAt := complaintverificationFields[6].Descriptor()
	// complaintverification.DefaultCreatedAt holds the default value on creation for the created_at field.
	complaintverification.DefaultCreatedAt = complaintverificationDescCreatedAt.Default.(func() time.Time)
	// complaintverificationDescUpdatedAt is the schema descriptor for updated_at field.
	complaintverificationDescUpdatedAt := complaintverificationFields[7].Descriptor()
	// complaintverification.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	complaintverification.DefaultUpdatedAt = complaintverificationDescUpdatedAt.Default.(func() time.Time)
	// complaintverification.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	complaintverification.UpdateDefaultUpdatedAt = complaintverificationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// complaintverificationDescID is the schema descriptor for id field.
	complaintverificationDescID := complaintverificationFields[0].Descriptor()
	// complaintverification.DefaultID holds the default value on creation for the id field.
	complaintverification.DefaultID = complaintverificationDescID.Default.(func() uuid.UUID)
	customerFields := schema.Customer{}.Fields()
	_ = customerFields
	// customerDescPhone is the schema descriptor for phone field.
	customerDescPhone := customerFields[2].Descriptor()
	// customer.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	customer.PhoneValidator = func() func(string) error {
		validators := customerDescPhone.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(phone string) error {
			for _, fn := range fns {
				if err := fn(phone); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// customerDescFirstName is the schema descriptor for first_name field.
	customerDescFirstName := customerFields[3].Descriptor()
	// customer.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	customer.FirstNameValidator = customerDescFirstName.Validators[0].(func(string) error)
	// customerDescLastName is the schema descriptor for last_name field.
	customerDescLastName := customerFields[4].Descriptor()
	// customer.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	customer.LastNameValidator = customerDescLastName.Validators[0].(func(string) error)
	// customerDescCreatedAt is the schema descriptor for created_at field.
	customerDescCreatedAt := customerFields[7].Descriptor()
	// customer.DefaultCreatedAt holds the default value on creation for the created_at field.
	customer.DefaultCreatedAt = customerDescCreatedAt.Default.(func() time.Time)
	// customerDescUpdatedAt is the schema descriptor for updated_at field.
	customerDescUpdatedAt := customerFields[8].Descriptor()
	// customer.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	customer.DefaultUpdatedAt = customerDescUpdatedAt.Default.(func() time.Time)
	// customer.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	customer.UpdateDefaultUpdatedAt = customerDescUpdatedAt.UpdateDefault.(func() time.Time)
	// customerDescID is the schema descriptor for id field.
	customerDescID := customerFields[0].Descriptor()
	// customer.DefaultID holds the default value on creation for the id field.
	customer.DefaultID = customerDescID.Default.(func() uuid.UUID)
	customeranalysisFields := schema.CustomerAnalysis{}.Fields()
	_ = customeranalysisFields
	// customeranalysisDescCreatedAt is the schema descriptor for created_at field.
	customeranalysisDescCreatedAt := customeranalysisFields[7].Descriptor()
	// customeranalysis.DefaultCreatedAt holds the default value on creation for the created_at field.
	customeranalysis.DefaultCreatedAt = customeranalysisDescCreatedAt.Default.(func() time.Time)
	// customeranalysisDescUpdatedAt is the schema descriptor for updated_at field.
	customeranalysisDescUpdatedAt := customeranalysisFields[8].Descriptor()
	// customeranalysis.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	customeranalysis.DefaultUpdatedAt = customeranalysisDescUpdatedAt.Default.(func() time.Time)
	// customeranalysis.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	customeranalysis.UpdateDefaultUpdatedAt = customeranalysisDescUpdatedAt.UpdateDefault.(func() time.Time)
	// customeranalysisDescID is the schema descriptor for id field.
	customeranalysisDescID := customeranalysisFields[0].Descriptor()
	// customeranalysis.DefaultID holds the default value on creation for the id field.
	customeranalysis.DefaultID = customeranalysisDescID.Default.(func() uuid.UUID)
}
