// Code generated by ent, DO NOT EDIT.

package customeranalysis

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the customeranalysis type in the database.
	Label = "customer_analysis"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldExternalUserID holds the string denoting the external_user_id field in the database.
	FieldExternalUserID = "external_user_id"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldConfidence holds the string denoting the confidence field in the database.
	FieldConfidence = "confidence"
	// FieldLastMessageAt holds the string denoting the last_message_at field in the database.
	FieldLastMessageAt = "last_message_at"
	// FieldAnalyzedAt holds the string denoting the analyzed_at field in the database.
	FieldAnalyzedAt = "analyzed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the customeranalysis in the database.
	Table = "customer_analyses"
)

// Columns holds all SQL columns for customeranalysis fields.
var Columns = []string{
	FieldID,
	FieldExternalUserID,
	FieldCategory,
	FieldSummary,
	FieldConfidence,
	FieldLastMessageAt,
	FieldAnalyzedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Category defines the type for the "category" enum field.
type Category string

// Category values.
const (
	CategoryPROGRAM_DELAY   Category = "PROGRAM_DELAY"
	CategoryPRICE           Category = "PRICE"
	CategorySUPPORT_QUALITY Category = "SUPPORT_QUALITY"
	CategoryTECHNICAL_ISSUE Category = "TECHNICAL_ISSUE"
	CategoryHEALTH_PERSONAL Category = "HEALTH_PERSONAL"
	CategoryLOST_INTEREST   Category = "LOST_INTEREST"
	CategoryUNCLEAR         Category = "UNCLEAR"
	CategoryNO_MESSAGES     Category = "NO_MESSAGES"
)

func (c Category) String() string {
	return string(c)
}

// CategoryValidator is a validator for the "category" field enum values. It is called by the builders before save.
func CategoryValidator(c Category) error {
	switch c {
	case CategoryPROGRAM_DELAY, CategoryPRICE, CategorySUPPORT_QUALITY, CategoryTECHNICAL_ISSUE, CategoryHEALTH_PERSONAL, CategoryLOST_INTEREST, CategoryUNCLEAR, CategoryNO_MESSAGES:
		return nil
	default:
		return fmt.Errorf("customeranalysis: invalid enum value for category field: %q", c)
	}
}

// Confidence defines the type for the "confidence" enum field.
type Confidence string

// ConfidenceLow is the default value of the Confidence enum.
const DefaultConfidence = ConfidenceLow

// Confidence values.
const (
	ConfidenceHigh   Confidence = "high"
	ConfidenceMedium Confidence = "medium"
	ConfidenceLow    Confidence = "low"
)

func (c Confidence) String() string {
	return string(c)
}

// ConfidenceValidator is a validator for the "confidence" field enum values. It is called by the builders before save.
func ConfidenceValidator(c Confidence) error {
	switch c {
	case ConfidenceHigh, ConfidenceMedium, ConfidenceLow:
		return nil
	default:
		return fmt.Errorf("customeranalysis: invalid enum value for confidence field: %q", c)
	}
}

// OrderOption defines the ordering options for the CustomerAnalysis queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByExternalUserID orders the results by the external_user_id field.
func ByExternalUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalUserID, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByConfidence orders the results by the confidence field.
func ByConfidence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfidence, opts...).ToFunc()
}

// ByLastMessageAt orders the results by the last_message_at field.
func ByLastMessageAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastMessageAt, opts...).ToFunc()
}

// ByAnalyzedAt orders the results by the analyzed_at field.
func ByAnalyzedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAnalyzedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
