// Code generated by ent, DO NOT EDIT.

package customeranalysis

import (
	"centropy-affilate/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldLTE(FieldID, id))
}

// ExternalUserID applies equality check predicate on the "external_user_id" field. It's identical to ExternalUserIDEQ.
func ExternalUserID(v uuid.UUID) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldEQ(FieldExternalUserID, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldEQ(FieldSummary, v))
}

// LastMessageAt applies equality check predicate on the "last_message_at" field. It's identical to LastMessageAtEQ.
func LastMessageAt(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldEQ(FieldLastMessageAt, v))
}

// AnalyzedAt applies equality check predicate on the "analyzed_at" field. It's identical to AnalyzedAtEQ.
func AnalyzedAt(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldEQ(FieldAnalyzedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldEQ(FieldUpdatedAt, v))
}

// ExternalUserIDEQ applies the EQ predicate on the "external_user_id" field.
func ExternalUserIDEQ(v uuid.UUID) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldEQ(FieldExternalUserID, v))
}

// ExternalUserIDNEQ applies the NEQ predicate on the "external_user_id" field.
func ExternalUserIDNEQ(v uuid.UUID) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNEQ(FieldExternalUserID, v))
}

// ExternalUserIDIn applies the In predicate on the "external_user_id" field.
func ExternalUserIDIn(vs ...uuid.UUID) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldIn(FieldExternalUserID, vs...))
}

// ExternalUserIDNotIn applies the NotIn predicate on the "external_user_id" field.
func ExternalUserIDNotIn(vs ...uuid.UUID) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNotIn(FieldExternalUserID, vs...))
}

// ExternalUserIDGT applies the GT predicate on the "external_user_id" field.
func ExternalUserIDGT(v uuid.UUID) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldGT(FieldExternalUserID, v))
}

// ExternalUserIDGTE applies the GTE predicate on the "external_user_id" field.
func ExternalUserIDGTE(v uuid.UUID) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldGTE(FieldExternalUserID, v))
}

// ExternalUserIDLT applies the LT predicate on the "external_user_id" field.
func ExternalUserIDLT(v uuid.UUID) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldLT(FieldExternalUserID, v))
}

// ExternalUserIDLTE applies the LTE predicate on the "external_user_id" field.
func ExternalUserIDLTE(v uuid.UUID) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldLTE(FieldExternalUserID, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v Category) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v Category) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...Category) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...Category) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNotIn(FieldCategory, vs...))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldContainsFold(FieldSummary, v))
}

// ConfidenceEQ applies the EQ predicate on the "confidence" field.
func ConfidenceEQ(v Confidence) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldEQ(FieldConfidence, v))
}

// ConfidenceNEQ applies the NEQ predicate on the "confidence" field.
func ConfidenceNEQ(v Confidence) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNEQ(FieldConfidence, v))
}

// ConfidenceIn applies the In predicate on the "confidence" field.
func ConfidenceIn(vs ...Confidence) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldIn(FieldConfidence, vs...))
}

// ConfidenceNotIn applies the NotIn predicate on the "confidence" field.
func ConfidenceNotIn(vs ...Confidence) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNotIn(FieldConfidence, vs...))
}

// LastMessageAtEQ applies the EQ predicate on the "last_message_at" field.
func LastMessageAtEQ(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldEQ(FieldLastMessageAt, v))
}

// LastMessageAtNEQ applies the NEQ predicate on the "last_message_at" field.
func LastMessageAtNEQ(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNEQ(FieldLastMessageAt, v))
}

// LastMessageAtIn applies the In predicate on the "last_message_at" field.
func LastMessageAtIn(vs ...time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldIn(FieldLastMessageAt, vs...))
}

// LastMessageAtNotIn applies the NotIn predicate on the "last_message_at" field.
func LastMessageAtNotIn(vs ...time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNotIn(FieldLastMessageAt, vs...))
}

// LastMessageAtGT applies the GT predicate on the "last_message_at" field.
func LastMessageAtGT(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldGT(FieldLastMessageAt, v))
}

// LastMessageAtGTE applies the GTE predicate on the "last_message_at" field.
func LastMessageAtGTE(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldGTE(FieldLastMessageAt, v))
}

// LastMessageAtLT applies the LT predicate on the "last_message_at" field.
func LastMessageAtLT(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldLT(FieldLastMessageAt, v))
}

// LastMessageAtLTE applies the LTE predicate on the "last_message_at" field.
func LastMessageAtLTE(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldLTE(FieldLastMessageAt, v))
}

// LastMessageAtIsNil applies the IsNil predicate on the "last_message_at" field.
func LastMessageAtIsNil() predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldIsNull(FieldLastMessageAt))
}

// LastMessageAtNotNil applies the NotNil predicate on the "last_message_at" field.
func LastMessageAtNotNil() predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNotNull(FieldLastMessageAt))
}

// AnalyzedAtEQ applies the EQ predicate on the "analyzed_at" field.
func AnalyzedAtEQ(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldEQ(FieldAnalyzedAt, v))
}

// AnalyzedAtNEQ applies the NEQ predicate on the "analyzed_at" field.
func AnalyzedAtNEQ(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNEQ(FieldAnalyzedAt, v))
}

// AnalyzedAtIn applies the In predicate on the "analyzed_at" field.
func AnalyzedAtIn(vs ...time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldIn(FieldAnalyzedAt, vs...))
}

// AnalyzedAtNotIn applies the NotIn predicate on the "analyzed_at" field.
func AnalyzedAtNotIn(vs ...time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNotIn(FieldAnalyzedAt, vs...))
}

// AnalyzedAtGT applies the GT predicate on the "analyzed_at" field.
func AnalyzedAtGT(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldGT(FieldAnalyzedAt, v))
}

// AnalyzedAtGTE applies the GTE predicate on the "analyzed_at" field.
func AnalyzedAtGTE(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldGTE(FieldAnalyzedAt, v))
}

// AnalyzedAtLT applies the LT predicate on the "analyzed_at" field.
func AnalyzedAtLT(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldLT(FieldAnalyzedAt, v))
}

// AnalyzedAtLTE applies the LTE predicate on the "analyzed_at" field.
func AnalyzedAtLTE(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldLTE(FieldAnalyzedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CustomerAnalysis) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CustomerAnalysis) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CustomerAnalysis) predicate.CustomerAnalysis {
	return predicate.CustomerAnalysis(sql.NotPredicates(p))
}
