// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdminUser is the predicate function for adminuser builders.
type AdminUser func(*sql.Selector)

// ComplaintVerification is the predicate function for complaintverification builders.
type ComplaintVerification func(*sql.Selector)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// CustomerAnalysis is the predicate function for customeranalysis builders.
type CustomerAnalysis func(*sql.Selector)
